# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(185, 162)
        self.help_button = QtWidgets.QPushButton(dialog)
        self.help_button.setGeometry(QtCore.QRect(130, 130, 51, 23))
        self.help_button.setObjectName("help_button")
        self.create_data = QtWidgets.QPushButton(dialog)
        self.create_data.setGeometry(QtCore.QRect(100, 10, 75, 23))
        self.create_data.setObjectName("create_data")
        self.textEdit = QtWidgets.QTextEdit(dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 50, 161, 41))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(dialog)
        self.create_data.clicked.connect(dialog.create_data)
        self.help_button.clicked.connect(dialog.help_button)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "中科银狐"))
        self.help_button.setText(_translate("dialog", "?"))
        self.create_data.setText(_translate("dialog", "数据展示"))
